### ISSUE TITLE
commit 934e90fe719c69d13d80b0ff797a4b22ca5a3462

### ISSUE THREAD

**Issue by Hilvcha** [Hilvcha/PA_competition#3]
```
日志详情
****************** start ********************** 
Traceback (most recent call last): 
File "pandas/_libs/parsers.pyx", line 1197, in pandas._libs.parsers.TextReader._convert_tokens TypeError: Cannot cast array from dtype('float64') to dtype('uint8') according to the rule 'safe' During handling of the above exception, another exception occurred: Traceback (most recent call last): 
File "/data/share/jingsuan/js_project/1825113747_1825113747/_PA_competition/main.py", line 12, in <module> trainSet, testSet = read_data(Configure.train_path, Configure.test_path) 
File "/data/share/jingsuan/js_project/1825113747_1825113747/_PA_competition/input/read_data.py", line 29, in read_data train = pd.read_csv(train_path, encoding='utf8', dtype=dtypes_train) 
File "/usr/local/python3/lib/python3.6/site-packages/pandas/io/parsers.py", line 709, in parser_f return _read(filepath_or_buffer, kwds) 
File "/usr/local/python3/lib/python3.6/site-packages/pandas/io/parsers.py", line 455, in _read data = parser.read(nrows) 
File "/usr/local/python3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1069, in read ret = self._engine.read(nrows) 
File "/usr/local/python3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1839, in read data = self._reader.read(nrows) 
File "pandas/_libs/parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read 
File "pandas/_libs/parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory 
File "pandas/_libs/parsers.pyx", line 1001, in pandas._libs.parsers.TextReader._read_rows 
File "pandas/_libs/parsers.pyx", line 1130, in pandas._libs.parsers.TextReader._convert_column_data 
File "pandas/_libs/parsers.pyx", line 1205, in pandas._libs.parsers.TextReader._convert_tokens 
ValueError: cannot safely convert passed user dtype of uint8 for float64 dtyped data in column 2
```

**Comment by Hilvcha** [comment]
fixed.
